package uz.vazifa.app.localization

object AppStrings {
    private val uz = mapOf(
        "app_name" to "Lider Vazifa",
        "app_subtitle" to "Xodimlar vazifalar tizimi",
        "login" to "Login",
        "password" to "Parol",
        "login_btn" to "Kirish",
        "login_error" to "Login yoki parol noto'g'ri",
        "show_password" to "Parolni ko'rsatish",
        "hide_password" to "Yashirish",
        "login_device_pending" to "Qurilma admin tasdig'ini kutmoqda",
        "login_network_error" to "Ulanish xatoligi",
        "notif_title" to "Ilovadan foydalanish uchun bildirishnomalarni yoqing",
        "notif_desc" to "Vazifalar va muddat eslatmalari push orqali yuboriladi. Ruxsatsiz ilova ishlamaydi.",
        "notif_open_settings" to "Sozlamalarni ochish",
        "notif_check" to "Tekshirish",
        "nav_home" to "Asosiy",
        "nav_tasks" to "Vazifalar",
        "nav_profile" to "Profil",
        "dash_title" to "Asosiy",
        "dash_employees" to "Xodimlar",
        "dash_active" to "Faol",
        "dash_completed" to "Bajarilgan",
        "dash_overdue" to "Kechikkan",
        "dash_recent_tasks" to "So'nggi vazifalar",
        "tasks_title" to "Vazifalarim",
        "task_detail" to "Vazifa",
        "task_deadline" to "Muddat",
        "task_create" to "Yangi vazifa",
        "task_name" to "Nomi",
        "task_desc" to "Tavsif",
        "task_deadline_hours" to "Muddat (soat)",
        "task_assignees" to "Mas'ul xodimlar",
        "task_create_btn" to "Yaratish",
        "profile_title" to "Profil",
        "profile_theme" to "Tema o'zgartirish",
        "profile_language" to "Til",
        "profile_logout" to "Chiqish",
        "com_settings" to "Sozlamalar",
        "com_theme_dark" to "Qorong'u rejim",
        "com_theme_light" to "Yorug' rejim",
        "com_theme_system" to "Tizim bo'yicha",
        "role_director" to "Direktor",
        "role_employee" to "Xodim",
        "status_new" to "Yangi",
        "status_accepted" to "Qabul qilindi",
        "status_in_progress" to "Jarayonda",
        "status_in_review" to "Tekshiruvda",
        "status_completed" to "Bajarildi",
        "status_rework" to "Qayta ishlash",
        "status_cancelled" to "Bekor qilindi",
        "com_cancel" to "Bekor qilish",
        "com_back" to "Orqaga",
        "com_save" to "Saqlash",
        "com_loading" to "Yuklanmoqda...",
    )

    private val uzKril = mapOf(
        "app_name" to "Lider Vazifa",
        "app_subtitle" to "Ходимлар вазифалар тизими",
        "login" to "Логин",
        "password" to "Парол",
        "login_btn" to "Кириш",
        "login_error" to "Логин ёки парол нотўғri",
        "show_password" to "Паролни кўрсатиш",
        "hide_password" to "Яшириш",
        "login_device_pending" to "Қурилма админ тасдиғини кутмоқда",
        "login_network_error" to "Уланиш хатолиги",
        "notif_title" to "Иловadan foydalanish учun bildirishnomalarni yoqing",
        "notif_desc" to "Vazifalar va muddat eslatmalari push orqali yuboriladi. Ruxsatsiz ilova ishlamaydi.",
        "notif_open_settings" to "Сozlamalarni ochish",
        "notif_check" to "Tekshirish",
        "nav_home" to "Асosiy",
        "nav_tasks" to "Vazifalar",
        "nav_profile" to "Profil",
        "dash_title" to "Асosiy",
        "dash_employees" to "Хodimlar",
        "dash_active" to "Faol",
        "dash_completed" to "Bajarilgan",
        "dash_overdue" to "Kechikkan",
        "dash_recent_tasks" to "So'nggi vazifalar",
        "tasks_title" to "Vazifalarim",
        "task_detail" to "Vazifa",
        "task_deadline" to "Muddat",
        "task_create" to "Yangi vazifa",
        "task_name" to "Nomi",
        "task_desc" to "Tavsif",
        "task_deadline_hours" to "Muddat (soat)",
        "task_assignees" to "Mas'ul xodimlar",
        "task_create_btn" to "Yaratish",
        "profile_title" to "Profil",
        "profile_theme" to "Mavzuni o'zgartirish",
        "profile_language" to "Til",
        "profile_logout" to "Chiqish",
        "com_settings" to "Sozlamalar",
        "com_theme_dark" to "Qorong'u rejim",
        "com_theme_light" to "Yorug' rejim",
        "com_theme_system" to "Tizim bo'yicha",
        "role_director" to "Direktor",
        "role_employee" to "Xodim",
        "status_new" to "Yangi",
        "status_accepted" to "Qabul qilindi",
        "status_in_progress" to "Jarayonda",
        "status_in_review" to "Tekshiruvda",
        "status_completed" to "Bajarildi",
        "status_rework" to "Qayta ishlash",
        "status_cancelled" to "Bekor qilindi",
        "com_cancel" to "Bekor qilish",
        "com_back" to "Orqaga",
        "com_save" to "Saqlash",
        "com_loading" to "Yuklanmoqda...",
    )
