package uz.vazifa.app.localization

object AppStrings {
    private val uz = mapOf(
        "app_name" to "Lider Vazifa",
        "app_subtitle" to "Xodimlar vazifalar tizimi",
        "login" to "Login",
        "phone" to "Telefon",
        "login_mode_phone" to "Telefon",
        "login_mode_login" to "Login",
        "login_empty" to "Telefon/login va parolni kiriting",
        "password" to "Parol",
        "login_btn" to "Kirish",
        "login_error" to "Login/telefon yoki parol noto'g'ri",
        "show_password" to "Parolni ko'rsatish",
        "hide_password" to "Yashirish",
        "login_device_pending" to "Qurilma admin tasdig'ini kutmoqda",
        "login_network_error" to "Ulanish xatoligi",
        "notif_title" to "Ilovadan foydalanish uchun bildirishnomalarni yoqing",
        "notif_desc" to "Vazifalar va muddat eslatmalari push orqali yuboriladi. Ruxsatsiz ilova ishlamaydi.",
        "notif_open_settings" to "Sozlamalarni ochish",
        "notif_check" to "Tekshirish",
        "notif_still_off" to "Bildirishnomalar hali yoqilmagan. Sozlamalardan yoqing.",
        "notif_fcm_error" to "Push token olinmadi. Internetni tekshiring va «Tekshirish»ni bosing.",
        "nav_home" to "Asosiy",
        "nav_tasks" to "Vazifalar",
        "nav_profile" to "Profil",
        "dash_title" to "Asosiy",
        "dash_employees" to "Xodimlar",
        "dash_active" to "Faol",
        "dash_completed" to "Bajarilgan",
        "dash_overdue" to "Kechikkan",
        "dash_recent_tasks" to "So'nggi vazifalar",
        "tasks_title" to "Vazifalarim",
        "task_detail" to "Vazifa",
        "task_deadline" to "Muddat",
        "task_create" to "Yangi vazifa",
        "task_name" to "Nomi",
        "task_desc" to "Tavsif",
        "task_deadline_hours" to "Muddat (soat)",
        "task_assignees" to "Mas'ul xodimlar",
        "task_create_btn" to "Yaratish",
        "profile_title" to "Profil",
        "profile_theme" to "Tema o'zgartirish",
        "profile_language" to "Til",
        "profile_logout" to "Chiqish",
        "com_settings" to "Sozlamalar",
        "com_theme_dark" to "Qorong'u rejim",
        "com_theme_light" to "Yorug' rejim",
        "com_theme_system" to "Tizim bo'yicha",
        "role_director" to "Direktor",
        "role_employee" to "Xodim",
        "status_new" to "Yangi",
        "status_accepted" to "Qabul qilindi",
        "status_in_progress" to "Jarayonda",
        "status_in_review" to "Tekshiruvda",
        "status_completed" to "Bajarildi",
        "status_rework" to "Qayta ishlash",
        "status_cancelled" to "Bekor qilindi",
        "com_cancel" to "Bekor qilish",
        "com_back" to "Orqaga",
        "com_save" to "Saqlash",
        "com_loading" to "Yuklanmoqda...",
    )

    private val uzKril = mapOf(
        "app_name" to "Lider Vazifa",
        "app_subtitle" to "Ходимлар вазифалар тизими",
        "login" to "Логин",
        "phone" to "Телефон",
        "login_mode_phone" to "Телефон",
        "login_mode_login" to "Логин",
        "login_empty" to "Телефон/логин ва паролни киритинг",
        "password" to "Парол",
        "login_btn" to "Кириш",
        "login_error" to "Логин/телефон ёки парол нотўғри",
        "show_password" to "Паролни кўрсатиш",
        "hide_password" to "Яшириш",
        "login_device_pending" to "Қурилма админ тасдиғини кутмоқда",
        "login_network_error" to "Уланиш хатолиги",
        "notif_title" to "Иловадан фойдаланиш учун билдиришномаларни ёқинг",
        "notif_desc" to "Вазифалар ва муддат еслатмалари пуш орқали йуборилади. Рухсатсиз илова ишламайди.",
        "notif_open_settings" to "Созламаларни очиш",
        "notif_check" to "Текшириш",
        "notif_still_off" to "Бildirishnomalar hali yoqilmagan. Sozlamalardan yoqing.",
        "notif_fcm_error" to "Push token olinmadi. Internetni tekshiring va «Tekshirish»ni bosing.",
        "nav_home" to "Асосий",
        "nav_tasks" to "Вазифалар",
        "nav_profile" to "Профил",
        "dash_title" to "Асосий",
        "dash_employees" to "Ходимлар",
        "dash_active" to "Фаол",
        "dash_completed" to "Бажарилган",
        "dash_overdue" to "Кечиккан",
        "dash_recent_tasks" to "Сўнгги вазифалар",
        "tasks_title" to "Вазифаларим",
        "task_detail" to "Вазифа",
        "task_deadline" to "Муддат",
        "task_create" to "Йанги вазифа",
        "task_name" to "Номи",
        "task_desc" to "Тавсиф",
        "task_deadline_hours" to "Муддат (соат)",
        "task_assignees" to "Масъул ходимлар",
        "task_create_btn" to "Йаратиш",
        "profile_title" to "Профил",
        "profile_theme" to "Тема ўзгартириш",
        "profile_language" to "Тил",
        "profile_logout" to "Чиқиш",
        "com_settings" to "Созламалар",
        "com_theme_dark" to "Қоронғу режим",
        "com_theme_light" to "Йоруғ режим",
        "com_theme_system" to "Тизим бўйича",
        "role_director" to "Директор",
        "role_employee" to "Ходим",
        "status_new" to "Йанги",
        "status_accepted" to "Қабул қилинди",
        "status_in_progress" to "Жарайонда",
        "status_in_review" to "Текширувда",
        "status_completed" to "Бажарилди",
        "status_rework" to "Қайта ишлаш",
        "status_cancelled" to "Бекор қилинди",
        "com_cancel" to "Бекор қилиш",
        "com_back" to "Орқага",
        "com_save" to "Сақлаш",
        "com_loading" to "Йукланмоқда...",
    )

    private val ru = mapOf(
        "app_name" to "Lider Vazifa",
        "app_subtitle" to "Система управления задачами",
        "login" to "Логин",
        "phone" to "Телефон",
        "login_mode_phone" to "Телефон",
        "login_mode_login" to "Логин",
        "login_empty" to "Введите телефон/логин и пароль",
        "password" to "Пароль",
        "login_btn" to "Войти",
        "login_error" to "Неверный телефон/логин или пароль",
        "show_password" to "Показать пароль",
        "hide_password" to "Скрыть",
        "login_device_pending" to "Устройство ожидает подтверждения администратора",
        "login_network_error" to "Ошибка подключения",
        "notif_title" to "Включите уведомления для использования приложения",
        "notif_desc" to "Задачи и напоминания отправляются через push. Без разрешения приложение не работает.",
        "notif_open_settings" to "Открыть настройки",
        "notif_check" to "Проверить",
        "notif_still_off" to "Уведомления ещё выключены. Включите их в настройках.",
        "notif_fcm_error" to "Не удалось получить push-токен. Проверьте интернет и нажмите «Проверить».",
        "nav_home" to "Главная",
        "nav_tasks" to "Задачи",
        "nav_profile" to "Профиль",
        "dash_title" to "Главная",
        "dash_employees" to "Сотрудники",
        "dash_active" to "Активные",
        "dash_completed" to "Выполнено",
        "dash_overdue" to "Просрочено",
        "dash_recent_tasks" to "Последние задачи",
        "tasks_title" to "Мои задачи",
        "task_detail" to "Задача",
        "task_deadline" to "Срок",
        "task_create" to "Новая задача",
        "task_name" to "Название",
        "task_desc" to "Описание",
        "task_deadline_hours" to "Срок (часы)",
        "task_assignees" to "Ответственные",
        "task_create_btn" to "Создать",
        "profile_title" to "Профиль",
        "profile_theme" to "Сменить тему",
        "profile_language" to "Язык",
        "profile_logout" to "Выйти",
        "com_settings" to "Настройки",
        "com_theme_dark" to "Тёмная тема",
        "com_theme_light" to "Светлая тема",
        "com_theme_system" to "Как в системе",
        "role_director" to "Директор",
        "role_employee" to "Сотрудник",
        "status_new" to "Новая",
        "status_accepted" to "Принята",
        "status_in_progress" to "В процессе",
        "status_in_review" to "На проверке",
        "status_completed" to "Выполнена",
        "status_rework" to "Доработка",
        "status_cancelled" to "Отменена",
        "com_cancel" to "Отмена",
        "com_back" to "Назад",
        "com_save" to "Сохранить",
        "com_loading" to "Загрузка...",
    )

    fun t(lang: AppLanguage, key: String): String = when (lang) {
        AppLanguage.UZ -> uz[key]
        AppLanguage.UZ_KRIL -> uzKril[key]
        AppLanguage.RU -> ru[key]
    } ?: uz[key] ?: key
}
