package uz.vazifa.app.localization

object AppStrings {
    private val uz = mapOf(
        "app_name" to "Lider Vazifa",
        "app_subtitle" to "Xodimlar vazifalar tizimi",
        "login" to "Login",
        "phone" to "Telefon",
        "login_mode_phone" to "Telefon",
        "login_mode_login" to "Login",
        "login_empty" to "Telefon/login va parolni kiriting",
        "password" to "Parol",
        "login_btn" to "Kirish",
        "login_error" to "Login/telefon yoki parol noto'g'ri",
        "show_password" to "Parolni ko'rsatish",
        "hide_password" to "Yashirish",
        "login_device_pending" to "Qurilma admin tasdig'ini kutmoqda",
        "login_device_limit" to "Maksimal 2 ta qurilma. Admin bilan bog'laning",
        "login_network_error" to "Ulanish xatoligi",
        "notif_title" to "Ilovadan foydalanish uchun bildirishnomalarni yoqing",
        "notif_desc" to "Vazifalar va muddat eslatmalari push orqali yuboriladi. Ruxsatsiz ilova ishlamaydi.",
        "notif_open_settings" to "Sozlamalarni ochish",
        "notif_check" to "Tekshirish",
        "notif_still_off" to "Bildirishnomalar hali yoqilmagan. Sozlamalardan yoqing.",
        "notif_fcm_error" to "Push token olinmadi. Internetni tekshiring va «Tekshirish»ni bosing.",
        "nav_home" to "Asosiy",
        "nav_employees" to "Xodimlar",
        "nav_tasks" to "Vazifalar",
        "nav_dept_tasks" to "Bo'limlar vazifalari",
        "nav_profile" to "Profil",
        "dash_title" to "Asosiy",
        "dash_employees" to "Xodimlar",
        "dash_active" to "Faol",
        "dash_completed" to "Bajarilgan",
        "dash_overdue" to "Kechikkan",
        "dash_recent_tasks" to "So'nggi vazifalar",
        "dash_empty" to "Ma'lumot topilmadi",
        "dash_unit" to "ta",
        "dash_total" to "Jami",
        "tasks_title" to "Vazifalarim",
        "task_detail" to "Vazifa",
        "task_deadline" to "Muddat",
        "task_time_left_prefix" to "Qoldi",
        "task_time_overdue_prefix" to "Kechikdi",
        "task_time_day_short" to "kun",
        "task_time_hour_short" to "soat",
        "task_time_min_short" to "daqiqa",
        "task_create" to "Yangi vazifa",
        "task_name" to "Nomi",
        "task_desc" to "Tavsif",
        "task_deadline_hours" to "Muddat (soat, masalan 1.5)",
        "task_deadline_datetime" to "Muddat (sana va vaqt)",
        "task_deadline_pick_date" to "Sanani tanlang",
        "task_deadline_pick_time" to "Vaqtni tanlang",
        "task_search_employee" to "Ism yoki telefon bo'yicha qidirish",
        "task_assignees" to "Mas'ul xodimlar",
        "task_create_btn" to "Yaratish",
        "task_complete_btn" to "Bajarildi deb bildirish",
        "task_complete_comment" to "Izoh",
        "task_add_photo" to "Rasm qo'shish (ixtiyoriy)",
        "task_photo_gallery" to "Galereya",
        "task_photo_camera" to "Kamera",
        "task_photo_load_failed" to "Rasm yuklanmadi",
        "task_photos" to "Rasmlar",
        "task_attachments" to "Biriktirmalar",
        "task_voice_hold" to "Mikrofonni bosib turing — ovoz yozing",
        "task_voice_recording" to "Yozib olinmoqda...",
        "task_voice_release_send" to "Qo'yib yuboring — vazifa yuboriladi",
        "task_voice_too_short" to "Juda qisqa, qayta urinib ko'ring",
        "task_voice_message" to "Ovozli xabar",
        "task_voice_play" to "Tinglash",
        "task_complete_with_text" to "Yozma hisobot (ixtiyoriy)",
        "task_comments" to "Izohlar",
        "task_assignee_status" to "Xodimlar holati",
        "task_from" to "Kimdan",
        "dept_task_from" to "Kim bergan",
        "dept_task_to" to "Kimga",
        "task_assigned_to_you" to "Sizga topshirilgan vazifa",
        "task_you_assigned" to "Siz bergan vazifa",
        "tasks_tab_new" to "Yangi",
        "tasks_tab_completed" to "Bajarilgan",
        "task_time_remaining" to "Qolgan vaqt",
        "task_assigned_at" to "Topshirilgan vaqti",
        "task_time_given" to "Ajratilgan muddat",
        "task_completed_at" to "Bajarilgan vaqti",
        "task_duration_day" to "kun",
        "task_duration_hour" to "soat",
        "task_duration_minute" to "daqiqa",
        "task_status" to "Holat",
        "task_report_submit" to "Yuborish",
        "task_assignee_hint" to "Bir nechta xodim tanlash mumkin",
        "task_selected_count" to "Tanlangan",
        "task_show_more_assignees" to "Yana ko'rsatish",
        "task_show_less_assignees" to "Yig'ish",
        "task_title_empty" to "Vazifa nomini kiriting",
        "task_assignee_required" to "Kamida bitta xodim tanlang",
        "task_create_failed" to "Vazifa yaratilmadi. Qayta urinib ko'ring",
        "task_create_forbidden" to "Ruxsat yo'q yoki bildirishnomalar o'chirilgan",
        "task_photo_upload_failed" to "Vazifa yaratildi, lekin rasm yuklanmadi",
        "task_create_for_employee" to "Xodimga vazifa berish",
        "task_edit" to "Vazifani o'zgartirish",
        "task_delete" to "O'chirish",
        "task_delete_confirm" to "Vazifani bekor qilasizmi?",
        "task_update_failed" to "Vazifa yangilanmadi. Qayta urinib ko'ring",
        "task_edit_completed_forbidden" to "Bajarilgan vazifani o'zgartirib bo'lmaydi",
        "emp_select_all" to "Hammasi",
        "emp_all_departments" to "Bo'limlar hammasi",
        "emp_department" to "Bo'lim",
        "emp_online" to "Onlayn",
        "emp_last_seen_prefix" to "Oxirgi faollik",
        "emp_last_seen_never" to "Hali kirmagan",
        "emp_last_seen_just_now" to "Hozirgina",
        "emp_last_seen_ago" to "oldin",
        "emp_last_seen_yesterday" to "Kecha",
        "emp_deselect_all" to "Bekor qilish",
        "emp_total" to "Jami vazifalar",
        "emp_on_time" to "O'z vaqtida",
        "emp_completion" to "Bajarilish",
        "emp_task_history" to "Vazifalar tarixi",
        "emp_no_tasks" to "Hali vazifa berilmagan",
        "profile_title" to "Profil",
        "profile_theme" to "Tema o'zgartirish",
        "profile_language" to "Til",
        "profile_logout" to "Chiqish",
        "profile_change_password" to "Parolni o'zgartirish",
        "profile_current_password" to "Joriy parol",
        "profile_new_password" to "Yangi parol",
        "profile_confirm_password" to "Parolni tasdiqlash",
        "profile_password_changed" to "Parol yangilandi",
        "profile_wrong_current_password" to "Joriy parol noto'g'ri",
        "profile_password_mismatch" to "Parollar mos kelmadi",
        "profile_password_min_length" to "Yangi parol kamida 6 belgi",
        "profile_password_empty" to "Barcha maydonlarni to'ldiring",
        "com_settings" to "Sozlamalar",
        "com_theme_dark" to "Qorong'u rejim",
        "com_theme_light" to "Yorug' rejim",
        "com_theme_system" to "Tizim bo'yicha",
        "role_director" to "Direktor",
        "role_employee" to "Xodim",
        "status_new" to "Yangi",
        "status_accepted" to "Qabul qilindi",
        "status_in_progress" to "Jarayonda",
        "status_in_review" to "Tekshiruvda",
        "status_completed" to "Bajarildi",
        "status_rework" to "Qayta ishlash",
        "status_cancelled" to "Bekor qilindi",
        "com_cancel" to "Bekor qilish",
        "com_back" to "Orqaga",
        "com_save" to "Saqlash",
        "com_loading" to "Yuklanmoqda...",
    )

    private val uzKril = mapOf(
        "app_name" to "Lider Vazifa",
        "app_subtitle" to "Ходимлар вазифалар тизими",
        "login" to "Логин",
        "phone" to "Телефон",
        "login_mode_phone" to "Телефон",
        "login_mode_login" to "Логин",
        "login_empty" to "Телефон/логин ва паролни киритинг",
        "password" to "Парол",
        "login_btn" to "Кириш",
        "login_error" to "Логин/телефон ёки парол нотўғри",
        "show_password" to "Паролни кўрсатиш",
        "hide_password" to "Яшириш",
        "login_device_pending" to "Қурилма админ тасдиғини кутмоқда",
        "login_device_limit" to "Максимум 2 та қурилма. Админ билан боғланинг",
        "login_network_error" to "Уланиш хатолиги",
        "notif_title" to "Иловадан фойдаланиш учун билдиришномаларни ёқинг",
        "notif_desc" to "Вазифалар ва муддат еслатмалари пуш орқали йуборилади. Рухсатсиз илова ишламайди.",
        "notif_open_settings" to "Созламаларни очиш",
        "notif_check" to "Текшириш",
        "notif_still_off" to "Билдиришномалар ҳали ёқилмаган. Созламалардан ёқинг.",
        "notif_fcm_error" to "Пуш токен олинмади. Интернетни текширинг ва «Текшириш»ни босинг.",
        "nav_home" to "Асосий",
        "nav_employees" to "Ходимлар",
        "nav_tasks" to "Вазифалар",
        "nav_dept_tasks" to "Бўлимлар вазифалари",
        "nav_profile" to "Профил",
        "dash_title" to "Асосий",
        "dash_employees" to "Ходимлар",
        "dash_active" to "Фаол",
        "dash_completed" to "Бажарилган",
        "dash_overdue" to "Кечиккан",
        "dash_recent_tasks" to "Сўнгги вазифалар",
        "dash_empty" to "Маълумот топилмади",
        "dash_unit" to "та",
        "dash_total" to "Жами",
        "tasks_title" to "Вазифаларим",
        "task_detail" to "Вазифа",
        "task_deadline" to "Муддат",
        "task_time_left_prefix" to "Қолди",
        "task_time_overdue_prefix" to "Кечикди",
        "task_time_day_short" to "кун",
        "task_time_hour_short" to "соат",
        "task_time_min_short" to "дақиқа",
        "task_create" to "Янги вазифа",
        "task_name" to "Номи",
        "task_desc" to "Тавсиф",
        "task_deadline_hours" to "Муддат (соат, масалан 1.5)",
        "task_deadline_datetime" to "Муддат (сана ва вақт)",
        "task_deadline_pick_date" to "Санани танланг",
        "task_deadline_pick_time" to "Вақтни танланг",
        "task_search_employee" to "Исм ёки телефон бўйича қидириш",
        "task_assignees" to "Масъул ходимлар",
        "task_create_btn" to "Яратиш",
        "task_complete_btn" to "Бажарилди деб билдириш",
        "task_complete_comment" to "Изоҳ",
        "task_add_photo" to "Расм қўшиш (ихтиёрий)",
        "task_photo_gallery" to "Галерея",
        "task_photo_camera" to "Камера",
        "task_photo_load_failed" to "Расм юкланмади",
        "task_photos" to "Расмлар",
        "task_attachments" to "Бириктирмалар",
        "task_voice_hold" to "Микрофонни босиб туринг — овоз ёзинг",
        "task_voice_recording" to "Ёзиб олинмоқда...",
        "task_voice_release_send" to "Қўйиб юборинг — вазифа юборилади",
        "task_voice_too_short" to "Жуда қисқа, қайта уриниб кўринг",
        "task_voice_message" to "Овозли хабар",
        "task_voice_play" to "Тинглаш",
        "task_complete_with_text" to "Ёзма ҳисобот (ихтиёрий)",
        "task_comments" to "Изоҳлар",
        "task_assignee_status" to "Ходимлар ҳолати",
        "task_from" to "Кимдан",
        "dept_task_from" to "Ким берган",
        "dept_task_to" to "Кимга",
        "task_assigned_to_you" to "Сизга топширилган вазифа",
        "task_you_assigned" to "Сиз берган вазифа",
        "tasks_tab_new" to "Янги",
        "tasks_tab_completed" to "Бажарилган",
        "task_time_remaining" to "Қолган вақт",
        "task_assigned_at" to "Топширилган вақти",
        "task_time_given" to "Ажратилган муддат",
        "task_completed_at" to "Бажарилган вақти",
        "task_duration_day" to "кун",
        "task_duration_hour" to "соат",
        "task_duration_minute" to "дақиқа",
        "task_status" to "Ҳолат",
        "task_report_submit" to "Юбориш",
        "task_assignee_hint" to "Бир нечта ходим танлаш мумкин",
        "task_selected_count" to "Танланган",
        "task_show_more_assignees" to "Яна кўрсатиш",
        "task_show_less_assignees" to "Яшириш",
        "task_title_empty" to "Вазифа номини киритинг",
        "task_assignee_required" to "Камида битта ходим танланг",
        "task_create_failed" to "Вазифа яратилмади. Қайта уриниб кўринг",
        "task_create_forbidden" to "Рухсат йўқ ёки билдиришномалар ўчирилган",
        "task_photo_upload_failed" to "Вазифа яратилди, лекин расм юкланмади",
        "task_create_for_employee" to "Ходимга вазифа бериш",
        "task_edit" to "Вазифани ўзгартириш",
        "task_delete" to "Ўчириш",
        "task_delete_confirm" to "Вазифани бекор қиласизми?",
        "task_update_failed" to "Вазифа янгиланмади. Қайта уриниб кўринг",
        "task_edit_completed_forbidden" to "Бажарилган вазифани ўзгартириб бўлмайди",
        "emp_select_all" to "Ҳаммаси",
        "emp_all_departments" to "Бўлимлар ҳаммаси",
        "emp_department" to "Бўлим",
        "emp_online" to "Онлайн",
        "emp_last_seen_prefix" to "Охирги фаоллик",
        "emp_last_seen_never" to "Ҳали кирмаган",
        "emp_last_seen_just_now" to "Ҳозиргина",
        "emp_last_seen_ago" to "олдин",
        "emp_last_seen_yesterday" to "Кеча",
        "emp_deselect_all" to "Бекор қилиш",
        "emp_total" to "Жами вазифалар",
        "emp_on_time" to "Ўз вақтида",
        "emp_completion" to "Бажарилиш",
        "emp_task_history" to "Вазифалар тарихи",
        "emp_no_tasks" to "Ҳали вазифа берилмаган",
        "profile_title" to "Профил",
        "profile_theme" to "Тема ўзгартириш",
        "profile_language" to "Тил",
        "profile_logout" to "Чиқиш",
        "profile_change_password" to "Паролни ўзгартириш",
        "profile_current_password" to "Жорий парол",
        "profile_new_password" to "Янги парол",
        "profile_confirm_password" to "Паролни тасдиқлаш",
        "profile_password_changed" to "Парол янгиланди",
        "profile_wrong_current_password" to "Жорий парол нотўғри",
        "profile_password_mismatch" to "Пароллар мос келмади",
        "profile_password_min_length" to "Янги парол камида 6 белги",
        "profile_password_empty" to "Барча майдонларни тўлдиринг",
        "com_settings" to "Созламалар",
        "com_theme_dark" to "Қоронғу режим",
        "com_theme_light" to "Йоруғ режим",
        "com_theme_system" to "Тизим бўйича",
        "role_director" to "Директор",
        "role_employee" to "Ходим",
        "status_new" to "Янги",
        "status_accepted" to "Қабул қилинди",
        "status_in_progress" to "Жарайонда",
        "status_in_review" to "Текширувда",
        "status_completed" to "Бажарилди",
        "status_rework" to "Қайта ишлаш",
        "status_cancelled" to "Бекор қилинди",
        "com_cancel" to "Бекор қилиш",
        "com_back" to "Орқага",
        "com_save" to "Сақлаш",
        "com_loading" to "Юкланмоқда...",
    )

    private val ru = mapOf(
        "app_name" to "Lider Vazifa",
        "app_subtitle" to "Система управления задачами",
        "login" to "Логин",
        "phone" to "Телефон",
        "login_mode_phone" to "Телефон",
        "login_mode_login" to "Логин",
        "login_empty" to "Введите телефон/логин и пароль",
        "password" to "Пароль",
        "login_btn" to "Войти",
        "login_error" to "Неверный телефон/логин или пароль",
        "show_password" to "Показать пароль",
        "hide_password" to "Скрыть",
        "login_device_pending" to "Устройство ожидает подтверждения администратора",
        "login_device_limit" to "Максимум 2 устройства. Обратитесь к администратору",
        "login_network_error" to "Ошибка подключения",
        "notif_title" to "Включите уведомления для использования приложения",
        "notif_desc" to "Задачи и напоминания отправляются через push. Без разрешения приложение не работает.",
        "notif_open_settings" to "Открыть настройки",
        "notif_check" to "Проверить",
        "notif_still_off" to "Уведомления ещё выключены. Включите их в настройках.",
        "notif_fcm_error" to "Не удалось получить push-токен. Проверьте интернет и нажмите «Проверить».",
        "nav_home" to "Главная",
        "nav_employees" to "Сотрудники",
        "nav_tasks" to "Задачи",
        "nav_dept_tasks" to "Задачи отделов",
        "nav_profile" to "Профиль",
        "dash_title" to "Главная",
        "dash_employees" to "Сотрудники",
        "dash_active" to "Активные",
        "dash_completed" to "Выполнено",
        "dash_overdue" to "Просрочено",
        "dash_recent_tasks" to "Последние задачи",
        "dash_empty" to "Данные не найдены",
        "dash_unit" to "шт.",
        "dash_total" to "Всего",
        "tasks_title" to "Мои задачи",
        "task_detail" to "Задача",
        "task_deadline" to "Срок",
        "task_time_left_prefix" to "Осталось",
        "task_time_overdue_prefix" to "Просрочено",
        "task_time_day_short" to "дн",
        "task_time_hour_short" to "ч",
        "task_time_min_short" to "мин",
        "task_create" to "Новая задача",
        "task_name" to "Название",
        "task_desc" to "Описание",
        "task_deadline_hours" to "Срок (часы, например 1.5)",
        "task_deadline_datetime" to "Срок (дата и время)",
        "task_deadline_pick_date" to "Выберите дату",
        "task_deadline_pick_time" to "Выберите время",
        "task_search_employee" to "Поиск по имени или телефону",
        "task_assignees" to "Ответственные",
        "task_create_btn" to "Создать",
        "task_complete_btn" to "Отметить выполненной",
        "task_complete_comment" to "Комментарий",
        "task_add_photo" to "Добавить фото (необязательно)",
        "task_photo_gallery" to "Галерея",
        "task_photo_camera" to "Камера",
        "task_photo_load_failed" to "Не удалось загрузить фото",
        "task_photos" to "Фото",
        "task_attachments" to "Вложения",
        "task_voice_hold" to "Удерживайте микрофон для записи",
        "task_voice_recording" to "Запись...",
        "task_voice_release_send" to "Отпустите — задача будет отправлена",
        "task_voice_too_short" to "Слишком коротко, попробуйте снова",
        "task_voice_message" to "Голосовое сообщение",
        "task_voice_play" to "Слушать",
        "task_complete_with_text" to "Письменный отчёт (необязательно)",
        "task_comments" to "Комментарии",
        "task_assignee_status" to "Статус сотрудников",
        "task_from" to "От кого",
        "dept_task_from" to "Кто назначил",
        "dept_task_to" to "Кому",
        "task_assigned_to_you" to "Задача назначена вам",
        "task_you_assigned" to "Задача, которую вы назначили",
        "tasks_tab_new" to "Новые",
        "tasks_tab_completed" to "Выполненные",
        "task_time_remaining" to "Осталось времени",
        "task_assigned_at" to "Назначена",
        "task_time_given" to "Срок на выполнение",
        "task_completed_at" to "Выполнена",
        "task_duration_day" to "дн.",
        "task_duration_hour" to "ч.",
        "task_duration_minute" to "мин.",
        "task_status" to "Статус",
        "task_report_submit" to "Отправить",
        "task_assignee_hint" to "Можно выбрать несколько сотрудников",
        "task_selected_count" to "Выбрано",
        "task_show_more_assignees" to "Показать ещё",
        "task_show_less_assignees" to "Скрыть",
        "task_title_empty" to "Введите название задачи",
        "task_assignee_required" to "Выберите хотя бы одного сотрудника",
        "task_create_failed" to "Не удалось создать задачу. Попробуйте снова",
        "task_create_forbidden" to "Нет доступа или уведомления отключены",
        "task_photo_upload_failed" to "Задача создана, но фото не загрузилось",
        "task_create_for_employee" to "Назначить задачу сотруднику",
        "task_edit" to "Редактировать задачу",
        "task_delete" to "Удалить",
        "task_delete_confirm" to "Отменить задачу?",
        "task_update_failed" to "Не удалось обновить задачу. Попробуйте снова",
        "task_edit_completed_forbidden" to "Выполненную задачу нельзя изменить",
        "emp_select_all" to "Все",
        "emp_all_departments" to "Все отделы",
        "emp_department" to "Отдел",
        "emp_online" to "Онлайн",
        "emp_last_seen_prefix" to "Последняя активность",
        "emp_last_seen_never" to "Ещё не входил",
        "emp_last_seen_just_now" to "Только что",
        "emp_last_seen_ago" to "назад",
        "emp_last_seen_yesterday" to "Вчера",
        "emp_deselect_all" to "Снять",
        "emp_total" to "Всего задач",
        "emp_on_time" to "Вовремя",
        "emp_completion" to "Выполнение",
        "emp_task_history" to "История задач",
        "emp_no_tasks" to "Задач ещё не было",
        "profile_title" to "Профиль",
        "profile_theme" to "Сменить тему",
        "profile_language" to "Язык",
        "profile_logout" to "Выйти",
        "profile_change_password" to "Сменить пароль",
        "profile_current_password" to "Текущий пароль",
        "profile_new_password" to "Новый пароль",
        "profile_confirm_password" to "Подтвердите пароль",
        "profile_password_changed" to "Пароль обновлён",
        "profile_wrong_current_password" to "Неверный текущий пароль",
        "profile_password_mismatch" to "Пароли не совпадают",
        "profile_password_min_length" to "Новый пароль минимум 6 символов",
        "profile_password_empty" to "Заполните все поля",
        "com_settings" to "Настройки",
        "com_theme_dark" to "Тёмная тема",
        "com_theme_light" to "Светлая тема",
        "com_theme_system" to "Как в системе",
        "role_director" to "Директор",
        "role_employee" to "Сотрудник",
        "status_new" to "Новая",
        "status_accepted" to "Принята",
        "status_in_progress" to "В процессе",
        "status_in_review" to "На проверке",
        "status_completed" to "Выполнена",
        "status_rework" to "Доработка",
        "status_cancelled" to "Отменена",
        "com_cancel" to "Отмена",
        "com_back" to "Назад",
        "com_save" to "Сохранить",
        "com_loading" to "Загрузка...",
    )

    fun t(lang: AppLanguage, key: String): String {
        val primary = when (lang) {
            AppLanguage.UZ -> uz
            AppLanguage.UZ_KRIL -> uzKril
            AppLanguage.RU -> ru
        }
        return primary[key]
            ?: uzKril[key]
            ?: uz[key]
            ?: ru[key]
            .orEmpty()
    }
}
